[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "synaxis"
authors = [
    { name="G-Lauz", email="gabriel.lauzier@usherbrooke.ca" },
]
description = "A model-based design Python framework for topology-aware graph execution and dynamic system simulation."
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3",
  "Operating System :: OS Independent",
]
dynamic = ["version"]

[tool.setuptools.packages.find]
where = ["src"]
include = ["synaxis*"]

[project.urls]
Homepage = "https://github.com/G-Lauz/synaxis"
Issues = "https://github.com/G-Lauz/synaxis/issues"

[tool.setuptools.dynamic]
version = {file = "VERSION"}

[tool.black]
line-length = 120
target-version = ["py311", "py312", "py313"]
exclude = '''
/(
  \.toml
  |\.sh
  |\.git
  |\.ini
  |Dockerfile
)/
'''

[tool.isort]
profile = "black"
