[pytest]
addopts = --color=yes --durations=10 --showlocals -vv
filterwarnings = ignore::DeprecationWarning
testpaths = tests
norecursedirs = data docs .cache .git .ipnb_checkpoints .venv .vscode .zed
